<a href="https://colab.research.google.com/github/britneh/DS-Unit-2-Linear-Models/blob/master/Britne_H_LS_DS_212_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [3]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [4]:
df.dtypes

bathrooms               float64
bedrooms                  int64
created                  object
description              object
display_address          object
latitude                float64
longitude               float64
price                     int64
street_address           object
interest_level           object
elevator                  int64
cats_allowed              int64
hardwood_floors           int64
dogs_allowed              int64
doorman                   int64
dishwasher                int64
no_fee                    int64
laundry_in_building       int64
fitness_center            int64
pre-war                   int64
laundry_in_unit           int64
roof_deck                 int64
outdoor_space             int64
dining_room               int64
high_speed_internet       int64
balcony                   int64
swimming_pool             int64
new_construction          int64
terrace                   int64
exclusive                 int64
loft                      int64
garden_p

#Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
 

In [0]:
df['created'] = df['created'].astype('datetime64[ns]')

In [6]:
df.dtypes

bathrooms                      float64
bedrooms                         int64
created                 datetime64[ns]
description                     object
display_address                 object
latitude                       float64
longitude                      float64
price                            int64
street_address                  object
interest_level                  object
elevator                         int64
cats_allowed                     int64
hardwood_floors                  int64
dogs_allowed                     int64
doorman                          int64
dishwasher                       int64
no_fee                           int64
laundry_in_building              int64
fitness_center                   int64
pre-war                          int64
laundry_in_unit                  int64
roof_deck                        int64
outdoor_space                    int64
dining_room                      int64
high_speed_internet              int64
balcony                  

In [7]:
train = df [ df['created'] < '2016-06-01 00:00:00']
train.head(20)
train.shape

(31844, 34)

In [8]:
test = df[df['created']>'2016-05-31']
test.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0         1.5         3  ...                 0                    0
1         1.0         2  ...                 0                    0
11        1.0         1  ...                 0                    0
14        1.0         1  ...                 0                    0
24        2.0         4  ...                 0                    0

[5 rows x 34 columns]

#Engineer at least two new features. (See below for explanation & ideas.)
 

In [9]:
df[ 'Bed-Bath'] = df['bathrooms'] + df['bedrooms'] 
df.head()

bathrooms  bedrooms  ... common_outdoor_space Bed-Bath
0        1.5         3  ...                    0      4.5
1        1.0         2  ...                    0      3.0
2        1.0         1  ...                    0      2.0
3        1.0         1  ...                    0      2.0
4        1.0         4  ...                    0      5.0

[5 rows x 35 columns]

In [10]:
df['Latitudal Distance from Times Square'] = abs(df['latitude']- 40.7590) 
df.head()

bathrooms  bedrooms  ... Bed-Bath Latitudal Distance from Times Square
0        1.5         3  ...      4.5                               0.0445
1        1.0         2  ...      3.0                               0.0357
2        1.0         1  ...      2.0                               0.0202
3        1.0         1  ...      2.0                               0.0051
4        1.0         4  ...      5.0                               0.0651

[5 rows x 36 columns]

 # Fit a linear regression model with at least two features.

In [0]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [16]:
# 3. Arrange X features matrix & y target vector

features = ['Bed-Bath', 'Latitudal Distance from Times Square']
target = ['price']

x_train = df[features]
y_train = df[target]

x_train.shape, y_train.shape

((48817, 2), (48817, 1))

In [19]:
model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
BedBath = 3
distance = .01
x_test = [[ BedBath, distance ]]

y_pred = model.predict(x_test)
y_pred

array([[4109.9043757]])

# Get the model's coefficients and intercept.
 

In [21]:
#Coefficient
model.coef_

array([[   831.03472897, -15760.51327693]])

In [22]:
model.intercept_

array([1774.40532155])

#Get regression metrics RMSE, MAE, and  R2 , for both the train and test data.
 

In [0]:
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [29]:
#Mae train
guess = y_train.mean()
y_pred = [guess] * len(y_train)
mae = mean_absolute_error(y_train, y_pred)

mae

1201.532252154329

In [0]:
#MAE test
guess = y_train.mean()
y_pred = [guess] * len(y_train)
mae = mean_absolute_error(y_train, y_pred)

mae

#What's the best test MAE you can get? Share your score and features used with your cohort on Slack!